version: '3'
services:
  zookeeper_1:
    image: kiljoy001/solr_cluster:latest
    container_name: keeper-1
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/data
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
    networks:
      - solr_network
  
  solr1:
    image: solr:9.4
    container_name: solr1
    ports:
      - "8983:8983"
    environment:
      - ZK_HOST=zookeeper_1:2181
    depends_on:
      - zookeeper_1
    volumes:
      - solr_data1:/var/solr1
    networks:
      - solr_network
    command:
      - solr-fg
      - -DzkRun

  solr2:
    image: solr:9.4
    container_name: solr2
    ports:
      - "8984:8983"
    environment:
      - ZK_HOST=zookeeper_1:2181
    depends_on:
      - zookeeper_1
    volumes:
      - solr_data2:/var/solr2
    networks:
      - solr_network
    command:
      - solr-fg
      - -DzkRun

networks:
  solr_network:
    driver: bridge

volumes:
  zookeeper_data:
  solr_data1:
  solr_data2:  
